# -*- coding: utf-8 -*-
"""task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EKEwY7uM5FZoAJr74DVTLyAp4Rh2cU90
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df=pd.read_csv('sample_submission.csv')

X = df[['House Sq Foot', 'Bedrooms', 'Bathrooms']]
y = df['Price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)


model.feature_names_in_ = None

from sklearn.metrics import mean_squared_error, r2_score


# Make predictions on the testing data
y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared Score:", r2)

#testing

import matplotlib.pyplot as plt

# Scatter plot of actual vs. predicted prices
plt.scatter(y_test, y_pred)
plt.xlabel('Actual Price (USD)')
plt.ylabel('Predicted Price (USD)')
plt.title('Actual vs. Predicted House Prices')
plt.show()

# Residual analysis testing
plt.scatter(y_pred, y_test - y_pred)
plt.xlabel('Predicted Price (USD)')
plt.ylabel('Residuals (USD)')
plt.title('Residuals vs. Predicted Price')
plt.show()

bathrooms = 3
bedrooms = 4
sq_foot = 3000

# Make prediction
predicted_price = model.predict([[sq_foot, bedrooms, bathrooms]])

print("Predicted price of the house:", predicted_price[0])